"""
Oddsbanta — Autonomous Basketball Engine Configuration & League Registry
Phase 2: Data Acquisition & Canonical League Parameters

Invariant: Completely independent from football/tennis configs.
"""

from dataclasses import dataclass
from typing import Dict, Any, Optional, List


@dataclass(frozen=True)
class BasketballLeagueConfig:
    code: str
    name: str
    country: str
    quarter_minutes: int
    periods_count: int
    default_pace: float
    avg_offensive_rating: float
    espn_slug: Optional[str] = None
    livescore_keyword: Optional[str] = None
    livescore_keywords: tuple = ()
    hca_points: float = 2.85


# Official Global League Registry
LEAGUE_REGISTRY: Dict[str, BasketballLeagueConfig] = {
    # --- North America ---
    "NBA": BasketballLeagueConfig(
        code="NBA",
        name="National Basketball Association",
        country="USA",
        quarter_minutes=12,
        periods_count=4,
        default_pace=99.5,
        avg_offensive_rating=115.0,
        espn_slug="nba",
        livescore_keyword="nba",
        livescore_keywords=("nba", "pre-season"),
        hca_points=2.85,
    ),
    "WNBA": BasketballLeagueConfig(
        code="WNBA",
        name="Women's National Basketball Association",
        country="USA",
        quarter_minutes=10,
        periods_count=4,
        default_pace=80.5,
        avg_offensive_rating=104.0,
        espn_slug="wnba",
        livescore_keyword="wnba",
        livescore_keywords=("wnba",),
        hca_points=2.50,
    ),
    "NCAA_M": BasketballLeagueConfig(
        code="NCAA_M",
        name="NCAA Men's College Basketball",
        country="USA",
        quarter_minutes=20,
        periods_count=2,
        default_pace=68.5,
        avg_offensive_rating=105.0,
        espn_slug="mens-college-basketball",
        livescore_keyword="ncaa",
        livescore_keywords=("ncaa", "mens-college-basketball"),
        hca_points=3.20,
    ),
    "MEX_LNBP": BasketballLeagueConfig(
        code="MEX_LNBP",
        name="Liga Nacional de Baloncesto Profesional",
        country="Mexico",
        quarter_minutes=10,
        periods_count=4,
        default_pace=78.0,
        avg_offensive_rating=106.0,
        livescore_keyword="lnbp",
        livescore_keywords=("lnbp",),
        hca_points=2.90,
    ),

    # --- Europe & International Competitions ---
    "EUROLEAGUE": BasketballLeagueConfig(
        code="EUROLEAGUE",
        name="Turkish Airlines EuroLeague",
        country="International",
        quarter_minutes=10,
        periods_count=4,
        default_pace=72.0,
        avg_offensive_rating=110.0,
        livescore_keyword="euroleague",
        livescore_keywords=("euroleague",),
        hca_points=3.50,
    ),
    "EUROCUP": BasketballLeagueConfig(
        code="EUROCUP",
        name="BKT EuroCup",
        country="International",
        quarter_minutes=10,
        periods_count=4,
        default_pace=73.5,
        avg_offensive_rating=108.0,
        livescore_keyword="eurocup",
        livescore_keywords=("eurocup",),
        hca_points=3.10,
    ),
    "FIBA_BCL": BasketballLeagueConfig(
        code="FIBA_BCL",
        name="Basketball Champions League",
        country="International",
        quarter_minutes=10,
        periods_count=4,
        default_pace=73.5,
        avg_offensive_rating=107.5,
        livescore_keyword="champions league",
        livescore_keywords=("champions league", "bcl"),
        hca_points=3.00,
    ),
    "FIBA_FEC": BasketballLeagueConfig(
        code="FIBA_FEC",
        name="FIBA Europe Cup",
        country="International",
        quarter_minutes=10,
        periods_count=4,
        default_pace=74.0,
        avg_offensive_rating=106.0,
        livescore_keyword="fiba europe cup",
        livescore_keywords=("fiba europe cup",),
        hca_points=2.90,
    ),
    "ABA_LIGA": BasketballLeagueConfig(
        code="ABA_LIGA",
        name="ABA League",
        country="Adriatic",
        quarter_minutes=10,
        periods_count=4,
        default_pace=74.5,
        avg_offensive_rating=108.0,
        livescore_keyword="aba league",
        livescore_keywords=("aba league", "adriatic"),
        hca_points=3.40,
    ),
    "VTB_UL": BasketballLeagueConfig(
        code="VTB_UL",
        name="VTB United League",
        country="International",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=108.0,
        livescore_keyword="vtb united league",
        livescore_keywords=("vtb united league", "vtb"),
        hca_points=3.00,
    ),
    "BNXT": BasketballLeagueConfig(
        code="BNXT",
        name="BNXT League",
        country="International",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=105.0,
        livescore_keyword="bnxt",
        livescore_keywords=("bnxt league", "bnxt"),
        hca_points=2.85,
    ),
    "LAT_EST": BasketballLeagueConfig(
        code="LAT_EST",
        name="Latvian-Estonian Basketball League",
        country="International",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=105.0,
        livescore_keyword="latvian-estonian",
        livescore_keywords=("latvian-estonian",),
        hca_points=2.80,
    ),

    # --- Australia & Oceania ---
    "AUS_NBL": BasketballLeagueConfig(
        code="AUS_NBL",
        name="National Basketball League (NBL)",
        country="Australia",
        quarter_minutes=10,
        periods_count=4,
        default_pace=86.0,
        avg_offensive_rating=110.0,
        livescore_keyword="nbl",
        livescore_keywords=("nbl", "australia"),
        hca_points=2.75,
    ),
    "NZL_NBL": BasketballLeagueConfig(
        code="NZL_NBL",
        name="National Basketball League (New Zealand)",
        country="New Zealand",
        quarter_minutes=10,
        periods_count=4,
        default_pace=82.0,
        avg_offensive_rating=108.0,
        livescore_keyword="new zealand",
        livescore_keywords=("new zealand",),
        hca_points=2.75,
    ),

    # --- Poland ---
    "POL_PLK": BasketballLeagueConfig(
        code="POL_PLK",
        name="Orlen Basket Liga (PLK)",
        country="Poland",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=107.0,
        livescore_keyword="energa basket liga",
        livescore_keywords=("energa basket liga", "basket liga", "plk"),
        hca_points=2.90,
    ),
    "POL_W": BasketballLeagueConfig(
        code="POL_W",
        name="Orlen Basket Liga Kobiet",
        country="Poland",
        quarter_minutes=10,
        periods_count=4,
        default_pace=74.0,
        avg_offensive_rating=100.0,
        livescore_keyword="women's energa basket liga",
        livescore_keywords=("women's energa basket liga",),
        hca_points=2.60,
    ),

    # --- Czech Republic ---
    "CZE_NBL": BasketballLeagueConfig(
        code="CZE_NBL",
        name="Kooperativa NBL (Czech Republic)",
        country="Czech Republic",
        quarter_minutes=10,
        periods_count=4,
        default_pace=77.0,
        avg_offensive_rating=106.0,
        livescore_keyword="czech republic",
        livescore_keywords=("czech republic nbl", "czech"),
        hca_points=2.85,
    ),
    "CZE_ZBL": BasketballLeagueConfig(
        code="CZE_ZBL",
        name="Chance ZBL (Czech Women)",
        country="Czech Republic",
        quarter_minutes=10,
        periods_count=4,
        default_pace=74.0,
        avg_offensive_rating=99.0,
        livescore_keyword="zbl",
        livescore_keywords=("zbl",),
        hca_points=2.60,
    ),

    # --- Lithuania ---
    "LTU_LKL": BasketballLeagueConfig(
        code="LTU_LKL",
        name="Betsafe-LKL (Lithuania)",
        country="Lithuania",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=108.0,
        livescore_keyword="lkl",
        livescore_keywords=("lkl", "lithuania"),
        hca_points=3.10,
    ),

    # --- Spain ---
    "ESP_ACB": BasketballLeagueConfig(
        code="ESP_ACB",
        name="Liga Endesa (ACB)",
        country="Spain",
        quarter_minutes=10,
        periods_count=4,
        default_pace=74.0,
        avg_offensive_rating=108.0,
        livescore_keyword="acb",
        livescore_keywords=("liga acb", "acb"),
        hca_points=3.00,
    ),
    "ESP_FEB": BasketballLeagueConfig(
        code="ESP_FEB",
        name="Primera FEB (Spain 2nd Tier)",
        country="Spain",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=105.0,
        livescore_keyword="primera feb",
        livescore_keywords=("primera feb", "feb"),
        hca_points=2.80,
    ),

    # --- Italy ---
    "ITA_LBA": BasketballLeagueConfig(
        code="ITA_LBA",
        name="Lega Basket Serie A",
        country="Italy",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=107.0,
        livescore_keyword="serie a",
        livescore_keywords=("lega basket serie a", "serie a"),
        hca_points=2.90,
    ),
    "ITA_A2": BasketballLeagueConfig(
        code="ITA_A2",
        name="Serie A2 (Italy)",
        country="Italy",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.5,
        avg_offensive_rating=104.0,
        livescore_keyword="serie a2",
        livescore_keywords=("serie a2",),
        hca_points=2.80,
    ),
    "ITA_W": BasketballLeagueConfig(
        code="ITA_W",
        name="Women's Serie A1 (Italy)",
        country="Italy",
        quarter_minutes=10,
        periods_count=4,
        default_pace=73.0,
        avg_offensive_rating=100.0,
        livescore_keyword="women's serie a1",
        livescore_keywords=("women's serie a1",),
        hca_points=2.50,
    ),

    # --- Germany ---
    "GER_BBL": BasketballLeagueConfig(
        code="GER_BBL",
        name="Basketball Bundesliga (BBL)",
        country="Germany",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.5,
        avg_offensive_rating=108.0,
        livescore_keyword="bbl",
        livescore_keywords=("bbl", "bundesliga"),
        hca_points=2.80,
    ),

    # --- France ---
    "FRA_LNB": BasketballLeagueConfig(
        code="FRA_LNB",
        name="Betclic Élite (LNB Pro A)",
        country="France",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=107.0,
        livescore_keyword="lnb pro a",
        livescore_keywords=("lnb pro a", "pro a"),
        hca_points=2.90,
    ),
    "FRA_PROB": BasketballLeagueConfig(
        code="FRA_PROB",
        name="LNB Pro B (France)",
        country="France",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=104.0,
        livescore_keyword="pro b",
        livescore_keywords=("pro b",),
        hca_points=2.80,
    ),

    # --- Greece ---
    "GRE_GBL": BasketballLeagueConfig(
        code="GRE_GBL",
        name="Greek Basket League (GBL)",
        country="Greece",
        quarter_minutes=10,
        periods_count=4,
        default_pace=73.0,
        avg_offensive_rating=107.0,
        livescore_keyword="basket league",
        livescore_keywords=("basket league", "gbl"),
        hca_points=3.30,
    ),
    "GRE_A2": BasketballLeagueConfig(
        code="GRE_A2",
        name="Elite League (Greece A2)",
        country="Greece",
        quarter_minutes=10,
        periods_count=4,
        default_pace=74.0,
        avg_offensive_rating=103.0,
        livescore_keyword="a2",
        livescore_keywords=("a2", "elite league"),
        hca_points=2.90,
    ),

    # --- Turkiye ---
    "TUR_BSL": BasketballLeagueConfig(
        code="TUR_BSL",
        name="Basketbol Super Ligi (BSL)",
        country="Turkey",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=109.0,
        livescore_keyword="bsl",
        livescore_keywords=("bsl", "super ligi"),
        hca_points=3.20,
    ),

    # --- Serbia & Balkans ---
    "SRB_KLS": BasketballLeagueConfig(
        code="SRB_KLS",
        name="Basketball League of Serbia (KLS)",
        country="Serbia",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=105.0,
        livescore_keyword="basketball league of serbia",
        livescore_keywords=("basketball league of serbia", "serbia"),
        hca_points=3.20,
    ),
    "CRO_A1": BasketballLeagueConfig(
        code="CRO_A1",
        name="Favbet Premijer Liga (Croatia)",
        country="Croatia",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=104.0,
        livescore_keyword="premijer liga",
        livescore_keywords=("premijer liga", "croatia"),
        hca_points=2.90,
    ),
    "SLO_SKL": BasketballLeagueConfig(
        code="SLO_SKL",
        name="Liga Nova KBM (Slovenia)",
        country="Slovenia",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=104.0,
        livescore_keyword="liga nova kbm",
        livescore_keywords=("liga nova kbm", "slovenia"),
        hca_points=2.85,
    ),
    "SVK_SBL": BasketballLeagueConfig(
        code="SVK_SBL",
        name="Niké SBL (Slovakia)",
        country="Slovakia",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=104.0,
        livescore_keyword="sbl",
        livescore_keywords=("sbl", "slovakia"),
        hca_points=2.80,
    ),
    "MKD_FBL": BasketballLeagueConfig(
        code="MKD_FBL",
        name="Prva Liga (North Macedonia)",
        country="North Macedonia",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=103.0,
        livescore_keyword="prva liga",
        livescore_keywords=("prva liga", "macedonia"),
        hca_points=2.90,
    ),

    # --- Central & Northern Europe ---
    "AUT_BSL": BasketballLeagueConfig(
        code="AUT_BSL",
        name="win2day Basketball Superliga",
        country="Austria",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=104.0,
        livescore_keyword="superliga",
        livescore_keywords=("superliga", "austria"),
        hca_points=2.80,
    ),
    "HUN_NBI": BasketballLeagueConfig(
        code="HUN_NBI",
        name="Tippmix Férfi NB I. A (Hungary)",
        country="Hungary",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=105.0,
        livescore_keyword="nb i. a",
        livescore_keywords=("nb i. a", "hungary"),
        hca_points=2.90,
    ),
    "FIN_KOR": BasketballLeagueConfig(
        code="FIN_KOR",
        name="Korisliiga (Finland)",
        country="Finland",
        quarter_minutes=10,
        periods_count=4,
        default_pace=78.0,
        avg_offensive_rating=106.0,
        livescore_keyword="korisliiga",
        livescore_keywords=("korisliiga", "finland"),
        hca_points=2.80,
    ),
    "FIN_W": BasketballLeagueConfig(
        code="FIN_W",
        name="Korisliiga Women (Finland)",
        country="Finland",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=100.0,
        livescore_keyword="korisliiga women",
        livescore_keywords=("korisliiga women", "naisten i divisioona"),
        hca_points=2.50,
    ),
    "FIN_DIV1": BasketballLeagueConfig(
        code="FIN_DIV1",
        name="I Divisioona (Finland 2nd Tier)",
        country="Finland",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=102.0,
        livescore_keyword="i divisioona",
        livescore_keywords=("i divisioona",),
        hca_points=2.70,
    ),
    "DNK_BL": BasketballLeagueConfig(
        code="DNK_BL",
        name="Basketligaen (Denmark)",
        country="Denmark",
        quarter_minutes=10,
        periods_count=4,
        default_pace=77.0,
        avg_offensive_rating=105.0,
        livescore_keyword="basket ligaen",
        livescore_keywords=("basket ligaen", "kvindebasketligaen", "denmark"),
        hca_points=2.80,
    ),
    "NOR_BLNO": BasketballLeagueConfig(
        code="NOR_BLNO",
        name="BLNO (Norway)",
        country="Norway",
        quarter_minutes=10,
        periods_count=4,
        default_pace=77.0,
        avg_offensive_rating=104.0,
        livescore_keyword="blno",
        livescore_keywords=("blno", "kvinneligaen", "norway"),
        hca_points=2.75,
    ),
    "SWE_SBL": BasketballLeagueConfig(
        code="SWE_SBL",
        name="Svenska Basketligan (Sweden)",
        country="Sweden",
        quarter_minutes=10,
        periods_count=4,
        default_pace=77.0,
        avg_offensive_rating=106.0,
        livescore_keyword="basketligan",
        livescore_keywords=("basketligan", "sweden"),
        hca_points=2.85,
    ),
    "GBR_SLB": BasketballLeagueConfig(
        code="GBR_SLB",
        name="Super League Basketball (Great Britain)",
        country="Great Britain",
        quarter_minutes=10,
        periods_count=4,
        default_pace=78.0,
        avg_offensive_rating=106.0,
        livescore_keyword="slb",
        livescore_keywords=("slb", "great britain"),
        hca_points=2.80,
    ),

    # --- Eastern Europe & Mediterranean ---
    "ISR_BSL": BasketballLeagueConfig(
        code="ISR_BSL",
        name="Winner League (Israel)",
        country="Israel",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=108.0,
        livescore_keyword="super league",
        livescore_keywords=("super league", "israel"),
        hca_points=3.20,
    ),
    "CYP_OPAP": BasketballLeagueConfig(
        code="CYP_OPAP",
        name="OPAP Basket League (Cyprus)",
        country="Cyprus",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=103.0,
        livescore_keyword="a league",
        livescore_keywords=("a league", "cyprus"),
        hca_points=2.80,
    ),
    "BUL_NBL": BasketballLeagueConfig(
        code="BUL_NBL",
        name="National Basketball League (Bulgaria)",
        country="Bulgaria",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=104.0,
        livescore_keyword="bulgaria",
        livescore_keywords=("bulgaria", "bulgaria nbl"),
        hca_points=2.80,
    ),
    "UKR_FBU": BasketballLeagueConfig(
        code="UKR_FBU",
        name="FBU Superleague (Ukraine)",
        country="Ukraine",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=103.0,
        livescore_keyword="fbu superleague",
        livescore_keywords=("fbu superleague", "ukraine"),
        hca_points=2.80,
    ),
    "BLR_PL": BasketballLeagueConfig(
        code="BLR_PL",
        name="Premier League (Belarus)",
        country="Belarus",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=103.0,
        livescore_keyword="premier league",
        livescore_keywords=("premier league", "belarus"),
        hca_points=2.80,
    ),

    # --- Asia ---
    "JPN_BL": BasketballLeagueConfig(
        code="JPN_BL",
        name="B.League B1 (Japan)",
        country="Japan",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=106.0,
        livescore_keyword="b.league",
        livescore_keywords=("b.league", "japan"),
        hca_points=2.85,
    ),
    "KOR_KBL": BasketballLeagueConfig(
        code="KOR_KBL",
        name="Korean Basketball League (KBL)",
        country="South Korea",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.5,
        avg_offensive_rating=105.0,
        livescore_keyword="kbl",
        livescore_keywords=("kbl", "south korea"),
        hca_points=2.80,
    ),
    "PHI_PBA": BasketballLeagueConfig(
        code="PHI_PBA",
        name="Philippine Basketball Association (PBA)",
        country="Philippines",
        quarter_minutes=12,
        periods_count=4,
        default_pace=92.0,
        avg_offensive_rating=106.0,
        livescore_keyword="governors cup",
        livescore_keywords=("governors cup", "pba", "philippines"),
        hca_points=2.50,
    ),

    # --- South America ---
    "ARG_LNB": BasketballLeagueConfig(
        code="ARG_LNB",
        name="Liga Nacional de Básquet (Argentina)",
        country="Argentina",
        quarter_minutes=10,
        periods_count=4,
        default_pace=75.0,
        avg_offensive_rating=104.0,
        livescore_keyword="lnb",
        livescore_keywords=("lnb", "argentina"),
        hca_points=3.10,
    ),
    "BRA_NBB": BasketballLeagueConfig(
        code="BRA_NBB",
        name="Novo Basquete Brasil (NBB)",
        country="Brazil",
        quarter_minutes=10,
        periods_count=4,
        default_pace=76.0,
        avg_offensive_rating=105.0,
        livescore_keyword="nbb",
        livescore_keywords=("nbb", "brazil"),
        hca_points=3.00,
    ),
}

# Altitude Venues (Elevation Fatigue Bonus in Net Rating)
ALTITUDE_VENUES: Dict[str, float] = {
    "denver nuggets": 4.15,      # Ball Arena, Denver (~5,280 ft)
    "utah jazz": 3.90,           # Delta Center, Salt Lake City (~4,226 ft)
    "crvena zvezda": 3.80,       # Stark Arena, Belgrade (Hostile Atmosphere)
    "partizan": 3.80,            # Stark Arena, Belgrade (Hostile Atmosphere)
    "panathinaikos": 3.80,       # OAKA Altion, Athens (Hostile Atmosphere)
    "olympiacos": 3.80,          # Peace and Friendship Stadium, Piraeus
}

# Schedule Rest & Fatigue Modifiers
FATIGUE_MODIFIERS: Dict[str, float] = {
    "B2B_PENALTY": -2.80,           # Net rating drag on zero days rest
    "THREE_IN_FOUR_PENALTY": -3.60, # Net rating drag on 3 games in 4 nights
    "REST_ADVANTAGE_PER_DAY": 1.60, # Bonus per day of rest advantage
    "MAX_REST_ADVANTAGE": 4.50,     # Max cap on rest advantage differential
}
